---
title: "Tavole di Mortalità"
author: "Guarino Renata"
date: "2024-07-13"
output: 
  html_document
---

# Confronto dei Modelli di Mortalità: Lee-Carter vs Renshaw-Haberman

```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}


# Intro
# -------------------------------------------------------------------------
# Questa analisi utilizza il pacchetto R StMoMo per stimare la mortalità della
# popolazione maschile italiana, concentrando l'attenzione sulle età comprese
# tra 60 e 85 anni durante il periodo dal 1960 al 2010. Il dataset utilizzato
# è stato ottenuto dal Human Mortality Database (HMD) e comprende tavole di
# mortalità periodiche specifiche per l'Italia.
# 
# Il dataset HMD è disponibile presso il sito ufficiale del Human Mortality
# Database: [HMD Italia](https://www.mortality.org/Country/Country?cntr=ITA).
# 
# L'analisi si articola in due parti principali: prima, si applica il modello
# di Lee-Carter per esplorare la dinamica generale della mortalità in relazione
# all'età e al tempo. Successivamente, si adotta il modello di Renshaw e Haberman
# per confrontare e commentare le differenze con il modello di Lee-Carter,
# focalizzandosi sull'adattabilità ai dati specifici della popolazione in
# esame.
# 
# L'approccio metodologico include la preparazione dei dati attraverso il
# caricamento, la pulizia e la manipolazione per adattarsi ai modelli di
# mortalità. Verranno eseguiti test di bontà di adattamento e analisi dei
# residui per valutare l'efficacia predittiva dei modelli. Infine, saranno
# fornite interpretazioni sui risultati ottenuti, con particolare attenzione
# alla comprensione delle tendenze di mortalità osservate e alle implicazioni
# pratiche per l'attuazione di politiche pubbliche.
# -------------------------------------------------------------------------


# Carica i pacchetti necessari
library(ggplot2) # per la creazione di grafici eleganti e versatili
library(demography) # per l'analisi demografica e la modellizzazione della popolazione
library(tidyverse) # per la manipolazione dei dati e la visualizzazione.
library(StMoMo) # per la modellizzazione della mortalità utilizzando il metodo StMoMo
library(fds) # per la modellizzazione della mortalità basato su forcing functions.
library(tidyr) # per la manipolazione dei dati e la ristrutturazione dei dataframe.

# Carica il dataset specificando il separatore come ";"
data <- read.csv("Italy_Life_tables_period_1x1_Males.csv", sep=";")

# Verifica le prime righe per confermare che il dataset sia stato caricato correttamente
head(data)



# Prearazione e pulizia dei dati

# Informazioni sul dataset
str(data)

# Numero di righe e colonne nel dataset
dim(data)

# Verifica dei dati mancanti
colSums(is.na(data))

# Verifica della classe di ogni colonna nel dataset
classi_colonne <- sapply(data, class)
classi_colonne

# Verifica preliminare dei valori unici in Age
unique(data$Age)

# Rimuovi il simbolo "+" dalla colonna Age
data$Age <- gsub("\\+", "", data$Age)

# Converti la colonna Age in numerico
data$Age <- as.numeric(data$Age)

# Tratta i valori 110+ come 110, per evitare il msg "NA introdotti per coercizione"
data$Age[data$Age >= 110] <- 110

# Verifica dei valori unici in Age dopo la trasformazione
unique(data$Age)

# Verifica della classe di ogni colonna dopo la conversione
classi_colonne_dopo <- sapply(data, class)
print(classi_colonne_dopo)



# Filtraggio dei dati per età e anno

# Filtraggio dei soggetti dai 60 ai 85 anni dal 1960 al 2010
filtered_data <- subset(data, Year >= 1960 & Year <= 2010 & Age >= 60 & Age <= 85)

# Verifica delle prime righe del dataset filtrato
cat("Prime righe del dataset filtrato:\n")
head(filtered_data)
cat("\n")



# Creazione delle matrici di mortalità e popolazione

# Selezina le età e gli anni di interesse
eta <- 60:85
anni <- 1960:2010

# Crea la matrice di mortalità
data_mx <- matrix(NA, nrow = length(eta), ncol = length(anni))
pop_mx <- matrix(NA, nrow = length(eta), ncol = length(anni))

# Riempi le matrici data_mx e pop_mx con i dati appropriati
for (i in 1:length(eta)) {
  for (j in 1:length(anni)) {
    # Estrai il dato di mortalità (mx) e popolazione (lx) per ogni età e anno
    dato_mortalità <- filtered_data$mx[filtered_data$Age == eta[i] & filtered_data$Year == anni[j]]
    dato_popolazione <- filtered_data$lx[filtered_data$Age == eta[i] & filtered_data$Year == anni[j]]
    
    # Assegna i valori alle matrici
    data_mx[i, j] <- dato_mortalità
    pop_mx[i, j] <- dato_popolazione
  }

}


# Creazione dell'oggetto demogdata e StMoMoData

# Crea l'oggetto demogdata
dati_demogdata <- demogdata(data = data_mx,
                            pop = pop_mx,
                            ages = eta,
                            years = anni,
                            type = "mortality",
                            label = "Italy",
                            name = "Male")


# Converti l'oggetto demogdata in StMoMoData
dati_stmomo <- StMoMoData(dati_demogdata)





# Stima con i Modelli Lee-Carter e Renshaw-Haberman

# Adatta il modello di Lee-Carter
modello_LC <- lc()
fit_LC <- fit(modello_LC, data = dati_stmomo, ages.fit = eta)


# Adatta il modello di Renshaw e Haberman
modello_RH <- rh()
fit_RH <- fit(modello_RH, data = dati_stmomo, ages.fit = eta)


# Ottieni i risultati principali dei due Modelli
summary(fit_LC)
summary(fit_RH)


# Generazione delle previsioni per i due modelli
print(fit_LC)
print(fit_RH)

# Analisi dei modelli di mortalità stocastica

# I risultati sono stati ottenuti per valutare due modelli di mortalità, il modello Lee-Carter e il modello Renshaw e Haberman.
# Il modello Lee-Carter mostra un log-likelihood di -7753.99 e una deviance di 2730.59, con 101 parametri stimati.
# D'altra parte, il modello Renshaw e Haberman ha un log-likelihood di -6815.54 e una deviance di 853.7, con 176 parametri stimati.
# Questi risultati indicano che entrambi i modelli hanno un buon adattamento ai dati, ma il modello Renshaw e Haberman sembra mostrare un miglior adattamento basato su un log-likelihood leggermente superiore e una deviance inferiore rispetto al modello Lee-Carter.
# Tuttavia, va considerato che il modello Renshaw e Haberman è più complesso, con un numero maggiore di parametri stimati rispetto al modello Lee-Carter (176 vs 101).
# La scelta del modello migliore dovrebbe bilanciare l'adattamento ai dati con la complessità del modello e l'interpretazione dei parametri in relazione alle teorie demografiche pertinenti.




# Confronto dei Modelli di Mortalità: Residui e Previsioni

# Modello Lee-Carter vs. Modello Renshaw e Haberman

# Calcola i residui per il modello Lee-Carter
residui_LC <- residuals(fit_LC)

# Grafico dei residui del modello di Lee-Carter
plot(residui_LC, type = "scatter", reslim = c(-3.5, 3.5), col = "blue", main = "Residui - Modello Lee-Carter")

# Grafico 1: Residui vs Età

# Nel primo grafico, che rappresenta i residui in funzione dell'età, si nota una dispersione dei punti residui principalmente tra -2 e +2. 
# Questo indica che il modello Lee-Carter ha un'accuratezza accettabile per le diverse fasce di età (60-85 anni), con alcuni punti fuori dal range centrale che potrebbero suggerire una leggera variabilità nei dati non completamente catturata dal modello.

# Grafico 2: Residui vs Anno di Calendario

# Il secondo grafico mostra i residui in funzione dell'anno di calendario. Anche in questo caso, i residui sono principalmente concentrati tra -1 e +1, con una leggera dispersione al di fuori di questo range. 
# Questo suggerisce che il modello Lee-Carter ha una buona accuratezza nel tempo, ma ci sono ancora alcune variazioni che non riesce a modellare perfettamente.

# Grafico 3: Residui vs Anno di Nascita

# Il terzo grafico rappresenta i residui in funzione dell'anno di nascita. Qui si osserva una maggiore variabilità, con una distribuzione a forma di "M" che indica una concentrazione centrale più intensa di punti residui e code esterne più disperse. 
# Questo potrebbe suggerire che il modello Lee-Carter cattura meno bene le variazioni specifiche legate a diverse coorti di nascita.



# Grafico delle previsioni del modello di Lee-Carter
previsioni_LC <- forecast(fit_LC, h = 10)  # Previsioni per i prossimi 10 anni
plot(previsioni_LC, only.kt = TRUE)  # Grafico delle previsioni

# Interpretazione del Grafico delle Previsioni del Modello Lee-Carter

# Grafico: kappa_t^(1) vs. Anno

# Nel grafico delle previsioni del modello Lee-Carter, si nota l'andamento del parametro kappa_t^(1) in funzione dell'anno (dal 1960 al 2020).
# Questo parametro rappresenta la componente temporale principale del modello Lee-Carter, che cattura le variazioni nel tempo dei tassi di mortalità.

# Andamento Storico (1960-2010)

# Dal 1960 al 1980, la linea del kappa_t^(1) mostra una leggera tendenza decrescente con delle oscillazioni, indicando che i tassi di mortalità hanno avuto delle variazioni non uniformi ma con una tendenza generale al ribasso.
# Dal 1980 al 2010, si osserva una discesa più marcata e costante di kappa_t^(1). Questo suggerisce una diminuzione più rapida dei tassi di mortalità in questo periodo,
# che potrebbe essere attribuibile a miglioramenti nella medicina, nella sanità pubblica e nelle condizioni socio-economiche.

# Previsioni (2010-2020)

# Dopo il 2010, il grafico mostra un'area ombreggiata grigia che si allarga progressivamente. Questa area rappresenta l'intervallo di confidenza delle previsioni per kappa_t^(1).
# La linea centrale che continua attraverso l'area ombreggiata rappresenta la previsione puntuale di kappa_t^(1), mentre l'area grigia indica l'incertezza associata a queste previsioni.
# L'ampiezza crescente dell'area grigia suggerisce un aumento dell'incertezza man mano che ci si sposta nel futuro, il che è comune nelle previsioni a lungo termine.


### VS


# Calcolo dei residui per il modello Renshaw e Haberman
residui_RH <- residuals(fit_RH)

# Grafico dei residui del modello di Renshaw e Haberman
plot(residui_RH, type = "scatter", reslim = c(-3.5, 3.5), col = "darkred", main = "Residui - Modello Renshaw e Haberman")


# Residui vs. Età (age)

# Asse x: Età (60-85)
# Asse y: Residui (da -3.5 a 3.5)
# I residui sono distribuiti uniformemente intorno allo zero, simile al modello Lee-Carter, ma con una maggiore densità di punti tra -1 e +1.
# Questo indica una buona adattabilità del modello per diverse età.

# Residui vs. Anno di Calendario (calendar year)

# Asse x: Anni (1960-2010)
# Asse y: Residui (da -3.5 a 3.5)
# I residui mostrano una distribuzione concentrata intorno allo zero, con più variazione rispetto al modello Lee-Carter.
# Questo suggerisce che il modello si adatta bene nel tempo, ma potrebbe avere alcune deviazioni.

# Grafico: Residui vs. Anno di Nascita (year of birth)

# Asse x: Anno di Nascita (1880-1940)
# Asse y: Residui (da -3.5 a 3.5)

# La concentrazione dei punti residui è più densa intorno a zero, con una dispersione che si estende 
# principalmente tra -2 e +2, il che è un indicatore di una buon adattamento ai dati storici, senza un pattern evidente che suggerisca una deviazione sistematica significativa legata alle coorti di nascita.
# Ciò suggerisce che il modello gestisce le variazioni specifiche delle coorti di nascita in modo più efficiente rispetto al modello Lee-Carter.
# Tuttavia, ci sono ancora alcune variazioni che non vengono completamente catturate, come evidenziato 
# dai punti residui che si estendono oltre questi limiti.


# Grafico delle previsioni del modello di Renshaw e Haberman
previsioni_RH <- forecast(fit_RH, h = 10)  # Previsioni per i prossimi 10 anni
plot(previsioni_RH, only.kt = TRUE)  # Grafico delle previsioni

# Interpretazione del Grafico delle Previsioni del Modello Renshaw e Haberman

# Grafico: kappa_t^(1) vs. Anno

# Nel grafico delle previsioni del modello Renshaw e Haberman, si nota un andamento del parametro kappa_t^(1) 
# in funzione dell'anno (dal 1960 al 2020). Questo parametro rappresenta la componente temporale principale 
# del modello Renshaw e Haberman, catturando le variazioni temporali dei tassi di mortalità.

# Andamento Storico (1960-2010)

# Dal 1960 al 1980, la linea del kappa_t^(1) mostra un'andamento più irregolare 
#  rispetto al modello Lee-Carter, con delle oscillazioni, 
# indicando che i tassi di mortalità hanno avuto variazioni non uniformi in questo periodo.

# Dal 1980 al 2010, si osserva una tendenza decrescente di kappa_t^(1), ma con maggiore variabilità. 
# Questo suggerisce che i tassi di mortalità hanno continuato a diminuire, sebbene non in modo costante. 
# Le fluttuazioni indicano che ci sono stati periodi di variazione più pronunciata nei tassi di mortalità.

# Previsioni (2010-2020)

# Dopo il 2010, il grafico mostra un'area ombreggiata grigia che si allarga progressivamente. 
# Questa area rappresenta l'intervallo di confidenza delle previsioni per kappa_t^(1).
# La linea centrale che continua attraverso l'area ombreggiata rappresenta la previsione puntuale di kappa_t^(1), 
# mentre l'area grigia indica l'incertezza associata a queste previsioni.

# L'ampiezza dell'area grigia è più vasta per il modello Renshaw e Haberman rispetto al modello Lee-Carter, 
# indicando un aumento dell'incertezza nelle previsioni a lungo termine.




# Analisi Grafica dei Tassi di Mortalità Medi

# Calcola i tassi di mortalità medi
mortality_rates <- data_mx / pop_mx

# Converte la matrice in un dataframe
mortality_df <- data.frame(
  Age = rep(eta, each = length(anni)),
  Year = rep(anni, times = length(eta)),
  MortalityRate = as.vector(mortality_rates)
)

# Tassi di Mortalità Medi per Età
ggplot(mortality_df, aes(x = Year, y = MortalityRate)) +
  geom_line(aes(group = Age, color = factor(Age))) +
  labs(
    title = "Tassi di Mortalità Medi per Età",
    x = "Anno",
    y = "Tasso di Mortalità Medio"
  ) +
  theme_minimal()

# Descrizione del Grafico: Tassi di Mortalità Medi per Età

# Andamento Generale:
# Il grafico mostra una serie di linee che rappresentano i tassi di mortalità medi per diverse età,
# tracciati nel periodo dal 1960 al 2010.
# Si osserva un pattern ondulato per ciascuna linea di età, indicando fluttuazioni periodiche nei tassi di mortalità.

# Pattern Specifici:
# I tassi di mortalità medi sono più elevati per le età più avanzate, come indicato dalle linee che si trovano più in alto nel grafico (es. 85 anni).
# Le linee mostrano picchi significativi attorno agli anni 1980-1985 e 1995-2000 per molte fasce d'età,
# suggerendo eventi o condizioni particolari che hanno influito sui tassi di mortalità durante questi periodi.

# Variazioni Temporali:
# Nel periodo dal 1960 al 1970, i tassi di mortalità medi per le diverse età sembrano abbastanza stabili, con fluttuazioni minime.
# Dalla metà degli anni '70 fino agli anni '80, si notano aumenti più pronunciati nei tassi di mortalità per tutte le età,
# con un picco intorno al 1980-1985.
# Dopo questo picco, i tassi di mortalità medi tendono a diminuire nuovamente, ma con una certa irregolarità,
# fino a un nuovo aumento verso la fine degli anni '90.

# Impatto per Fasce d'Età:
# Le età più avanzate (ad esempio 85 anni) mostrano una maggiore variabilità e tassi di mortalità più elevati rispetto alle età più giovani (ad esempio 60 anni).
# Anche le età intermedie (ad esempio, 70-75 anni) mostrano fluttuazioni significative, ma non così pronunciate come quelle delle età più avanzate.

# Trends a Lungo Termine:
# Sebbene ci siano variazioni annuali, il trend generale dal 1960 al 2010 mostra una leggera riduzione nei tassi di mortalità medi per le età più giovani (60-70 anni),
# mentre le età più avanzate mostrano una riduzione meno marcata.


# Tassi di Mortalità Medi per Anno
ggplot(mortality_df, aes(x = Age, y = MortalityRate)) +
  geom_line(aes(group = Year, color = factor(Year))) +
  labs(
    title = "Tassi di Mortalità Medi per Anno",
    x = "Età",
    y = "Tasso di Mortalità Medio"
  ) +
  theme_minimal()

# Descrizione del Grafico: Tassi di Mortalità Medi per Anno

# Andamento Generale:

# Il grafico mostra una serie di linee che rappresentano i tassi di mortalità medi per diversi anni,
# tracciati per le età comprese tra 60 e 85 anni.
# Si osserva un pattern ondulato per ciascuna linea annuale, indicando fluttuazioni periodiche nei tassi di mortalità in funzione dell'età.

# Pattern Specifici:

# I tassi di mortalità medi sono più elevati per le età più giovani (60-65 anni) e diminuiscono man mano che l'età aumenta,
# fino a circa 75 anni, dopodiché tendono a stabilizzarsi o aumentare leggermente.
# Le linee mostrano picchi significativi intorno alle età 60-65 anni per molti anni, suggerendo una concentrazione di tassi di mortalità più elevati in queste fasce d'età.

# Variazioni Temporali:

# Gli anni tra il 1960 e il 1975 mostrano tassi di mortalità medi più elevati, con una tendenza generale alla riduzione dei tassi di mortalità negli anni successivi.
# Gli anni dopo il 1975, specialmente dal 1980 in poi, mostrano una diminuzione graduale dei tassi di mortalità medi,
# con fluttuazioni minori rispetto ai primi anni del periodo considerato.

# Impatto per Fasce d'Età:
# Le età comprese tra 60 e 65 anni mostrano tassi di mortalità medi più elevati rispetto alle età superiori.
# Dopo i 65 anni, i tassi di mortalità medi diminuiscono fino a circa 75 anni e poi tendono a stabilizzarsi o aumentare leggermente,
# indicando una riduzione del rischio di mortalità con l'avanzare dell'età fino a un certo punto.

# Trends a Lungo Termine:

# Sebbene ci siano variazioni annuali, il trend generale mostra una riduzione nei tassi di mortalità medi per tutte le età nel tempo.
# Gli anni più recenti (dopo il 2000) mostrano tassi di mortalità medi più bassi e stabili rispetto agli anni '60 e '70,
# suggerendo miglioramenti nelle condizioni di salute e nelle cure mediche.



# Analisi Grafica dei Tassi di Mortalità


# Definizione dei colori delle fasce per età
colors_age <- rainbow(length(unique(filtered_data$Age)))

# Definizione dei colori delle fasce per anno
colors_year <- heat.colors(length(unique(filtered_data$Year)))


# Tassi di mortalità per età

# Plot Tassi di Mortalità per Età
plt_age <- ggplot(filtered_data, aes(x = Year, y = mx, color = factor(Age))) +
  geom_line() +
  scale_color_manual(values = colors_age) +
  labs(
    title = "Tassi di Mortalità per Età",
    x = "Anno",
    y = "Log Tassi di Mortalità"
  ) +
  theme_minimal() +
  theme(legend.position = "right")

# Visualizza il plot per età
print(plt_age)

# Andamento Generale:

# Il grafico mostra i tassi di mortalità in scala logaritmica per diverse fasce di età, dai 60 agli 85 anni, dal 1960 al 2010.
# Ogni linea rappresenta una fascia di età specifica, indicata dalla legenda sulla destra del grafico.

# Pattern Specifici:

# Si osserva una diminuzione graduale dei tassi di mortalità logaritmici nel tempo per tutte le fasce di età.
# Le fasce di età più elevate (ad esempio, 85 anni) hanno tassi di mortalità più alti rispetto alle fasce di età più giovani (ad esempio, 60 anni).

# Variazioni Temporali:

# Negli anni '60 e '70, i tassi di mortalità sono generalmente più elevati, con una tendenza alla diminuzione nei decenni successivi.
# Dal 1980 in poi, i tassi di mortalità mostrano una riduzione più marcata, con un trend decrescente continuo fino al 2010.

# Impatto per Fasce d'Età:

# Le età più avanzate mostrano tassi di mortalità logaritmici più elevati rispetto alle età più giovani, con una differenza significativa tra le varie fasce d'età.
# Le fasce d'età intermedie (ad esempio, 70-75 anni) presentano tassi di mortalità che si posizionano tra quelli delle età più giovani e più avanzate.

# Trends a Lungo Termine:

# Il trend generale evidenzia una riduzione continua nei tassi di mortalità logaritmici per tutte le età dal 1960 al 2010.
# Questo suggerisce miglioramenti nei trattamenti medici, nelle condizioni di vita e nella sanità pubblica nel corso del periodo considerato.


# Tassi di mortalità per anno

# # Plot Tassi di Mortalità per Anno
ggplot(filtered_data, aes(x = Age, y = mx, color = factor(Year))) +
  geom_point() +
  scale_color_manual(values = colors_year) +
  labs(title = "Tassi di mortalità per anno",
       x = "Età",
       y = "Log tassi di mortalità",
       color = "Anno") +
  theme_minimal() +
  theme(legend.position = "right") +
  guides(color = guide_legend(title = "Anno"))

# Descrizione del Grafico: Tassi di Mortalità per Anno

# Andamento Generale:

# Il grafico rappresenta i tassi di mortalità in scala logaritmica per diverse fasce di età,
# dai 60 agli 85 anni, per ogni anno dal 1960 al 2009.
# I punti sono colorati in base all'anno, con un gradiente che va dal rosso (anni più vecchi) al giallo (anni più recenti).

# Pattern Specifici:

# Si osserva un incremento regolare dei tassi di mortalità con l'aumentare dell'età. Questo trend è coerente per tutti gli anni rappresentati.
# Per ciascuna età, i punti tendono a disporsi verticalmente in un pattern graduale, indicando la variazione del tasso di mortalità nel corso degli anni.

# Variazioni Temporali:

# Negli anni più vecchi (colori rosso scuro), i tassi di mortalità sono generalmente più elevati rispetto agli anni più recenti (colori giallo chiaro).
# Questo pattern suggerisce un miglioramento nei tassi di mortalità nel tempo, riflettendo probabilmente progressi nella sanità pubblica,
# nelle cure mediche e nelle condizioni di vita.

# Impatto per Fasce d'Età:

# I tassi di mortalità iniziano a un livello basso a 60 anni e aumentano costantemente fino a 85 anni, con una crescita più pronunciata nelle età più avanzate.
# Per ogni anno, la pendenza della curva aumenta con l'età, indicando che l'incremento del tasso di mortalità è esponenziale con l'età.

# Trends a Lungo Termine:

# C'è un chiaro trend discendente nei tassi di mortalità logaritmici negli anni più recenti rispetto agli anni più vecchi,
# evidenziando miglioramenti consistenti nei tassi di mortalità nel corso dei decenni.
# Il gradiente di colore rende visibile come i punti gialli (anni più recenti) tendano a essere posizionati più in basso rispetto ai punti rossi (anni più vecchi),
# per ogni gruppo di età.




# Commento conclusivo
# -------------------------------------------------------------------------
# L'analisi dei modelli di mortalità per gli uomini italiani ha permesso di
# osservare notevoli differenze tra il modello di Lee-Carter e quello di
# Renshaw e Haberman. Entrambi i modelli hanno dimostrato una buona adattabilità
# ai dati storici disponibili. Il modello di Renshaw e Haberman però, sembra offrire
# una migliore capacità di adattamento alle variazioni specifiche delle coorti
# di nascita, nonostante la maggiore complessità che richiede una valutazione
# attenta dei trade-off tra accuratezza e interpretabilità.
# 
# Le previsioni future indicano un trend continuo di miglioramento nei tassi
# di mortalità per gli uomini italiani, anche se con una certa variabilità
# nell'incertezza associata. Questi risultati sono cruciali per informare le
# decisioni politiche e le strategie sanitarie mirate, con l'obiettivo di
# migliorare ulteriormente le condizioni di vita e la salute della popolazione
# anziana in Italia.
# 
# In conclusione, l'analisi dei modelli di mortalità non solo fornisce insight
# sulla dinamica demografica italiana, ma costituisce anche un contributo
# significativo alla ricerca internazionale sulla mortalità e all'elaborazione
# di politiche basate su evidenze concrete.
# -------------------------------------------------------------------------

